apiVersion: batch/v1
kind: CronJob
metadata:
  name: Cron_request
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: App_2
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; curl http://192.168.49.2:31000/actuator 
          restartPolicy: OnFailure