apiVersion: v1
kind: Service
metadata:
  name: ipaas-service
  namespace: aplicacao
spec:
  type: NodePort
  selector:
    app: ipaas
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
