apiVersion: v1
kind: Service
metadata:
  name: ipaas
  namespace: aplicacao
  spec:
  selector: 
    app: ipaas
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000