apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronrequest
  namespace: aplicacao
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronrequest
            image: thiagolessa/ipaas_curl:1.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -X POST http://ipaas-service:80/log
          restartPolicy: OnFailure
