apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronrequest
  namespace: aplicacao
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronrequest
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -i http://clusterIP:31000/actuator/health/
          restartPolicy: OnFailure
